### ISSUE TITLE
In the manual there are many lightnesses in the detail and procedures.  When will this material be available? When will this material be available?

### ISSUE THREAD

**Issue by PMCONSULTINGSAP** [AniketMalik/ecommerce-store-support#11]
In the manual there are many lightnesses in the detail and procedures,, I have omitted large parts of it with the minimum necessary to try to run the main functionality, for now. It is important to be able to provide a video tutorial with the step by step for profiles from users with basic and intermediate knowledge. When will this material be available?

**Comment by AniketMalik** [comment]
Sir, As I have previously mentioned, the setup video was being produced but I got tested positive for corona virus and have high fever since 9 days. 

My recovery period still holds 7-10 days of medication. Once I recover from this illness, I'll resume the video tutorial.

Please allow me this recovery time for my health.

**Comment by PMCONSULTINGSAP** [comment]
Hello,

We are going to put the progress of this project on hold for a couple of weeks now, since you reiterate that you are in poor health. I hope you get better, take it easy and rest properly. Then we will see how things go if we can keep moving forward.

Bye.
Greetings

**Comment by AniketMalik** [comment]
Please check the comprehensive online documentation at:
[WooStore Pro Documentation](https://aniketmalik.github.io/woostore_pro_documentation/)
