### ISSUE TITLE
Android SDK

### ISSUE THREAD

**Issue by Ishan2610** [AniketMalik/ecommerce-store-support#22]
![h](https://user-images.githubusercontent.com/88072634/129452206-0600f6f7-289e-4605-89d1-ed5894994c6f.JPG)
Hi, I have deleted everything and installed it again on my main pc and followed each and every step, but still this error is coming, kindly help me fix it

Kind regards

**Comment by Ishan2610** [comment]
HI kindly reply, It extremely urgent!!

**Comment by AniketMalik** [comment]
The issue you are stating here will not hinder your development. Please move forward to the deployment. Flutter doctor issues mentioned above have been reported in flutter kit and are because of the sdk not the application. I too have the same android licence missing warning but it will not make any difference in the deployment. kindly move forward with the development. 

Also the setup you stated in #19 was completely correct which did not need any further assistance.

Furthermore please open an issue if you see an error in the application and not the sdk setup on your machine.

**Comment by Ishan2610** [comment]
Hi, so can i start editing my application and also, the images i sent you earlier were on another device, not my main device, and when i did the same steps on my main device, i encountered the MISSING JAVA MAIN CLASS issue

Kind regards

**Comment by AniketMalik** [comment]
The android tool chain licence warning can be neglected as it will not cause any issues. This warning is for some missing sdk part. If you want you can reinstall android studio. However i recommend that you leave it as it is and move on to deployment. It is not an issue, just a warning.
