### ISSUE TITLE
Issue with Wordpress Installation

### ISSUE THREAD

**Issue by Emicloud91** [AniketMalik/ecommerce-store-support#33]
Hi,

I've been trying to set the Application with my wordpress installation, everything went fine until I noticed that, when activating the plugin WooStore Pro Api my products are deleted from cart when I add them. This happens after adding 4-9 products and the cart gets empty. I'm using the last version, just updated today, but this is happening after version 1.9.4

Here's my loooong plugin list and I don't really know how to find what's causing the bug. And also a small video trying to explain what's going on...sorry for my english.

![image](https://user-images.githubusercontent.com/4982779/131171130-5b8ef558-21ed-4802-841a-9095bebe4bd6.png)

VIDEO EXPLAINING THE PROBLEM: https://youtu.be/gHanWrDXZ-k

Thanks for the support.

**Comment by AniketMalik** [comment]
Do you use any caching plugin for your website ?
Can you please disable it and then try again.

**Comment by Emicloud91** [comment]
Hi, 
At the moment there's no any caching plugin in my website. :( A quick question, for the new version, do it need to disable all the older plugins and keep only the WooStore Api one?

**Comment by AniketMalik** [comment]
No, only the cocart functionality has been included in the plugin.

Can you please try to create a new account with the cocart plugin activated
and then check if the issue persists.

**Comment by Emicloud91** [comment]
Hi,

Yeah, the problem still persist and it's also present for users who access the site and wish to log in when they are going to pay (after filling their cart)...and with this issue that isn't possible, while having the CoCart plugin.

**Comment by AniketMalik** [comment]
Alright so the problem is that the user's cart are not merging on the way to checkout if they wish to log in after adding the products in the cart while they were logged out.

Is that the correct explanation ?

**Comment by Emicloud91** [comment]
Uhmmm not a 100%...the problem is that, while the CoCart plugin is active in Wordpress (or the WooStore Api, in the latest version) there's a "bug" where the clients (logged or not) that are trying to add products to their cart cannot do it, as it gets emptied after randomly add products or browse the site...it's a random behavior.

A step by step recreation would be:
1 - Client access to the store (logged or not)
2 - Client tries to add a product to the cart - It works.
3 - Client keeps adding products to the cart - it can work
4 - Suddently if the client changes the page, searches or adds a new product to the cart, everything gets deleted.
5 - If the admin disables the plugin (CoCart or WooStore plugin), the previous products are back to the cart and the client can continue the purchase.

Thanks...

**Comment by AniketMalik** [comment]
Is this behaviour on the website or the mobile application ?

Please send me your website url to test it out as the cocart plugin does
not modify the cart items directly but only logs them in a different table
altogether. Also please add me to your wordpress dashboard to check out the
plugins so that I can know if any other plugin might be interfering with
the cart items.

**Comment by Emicloud91** [comment]
Hi, 

Sorry for the delay, I had to travel and was out for some days...How can I send you the access to my wordpress so you can check? 

It happens in both desktop and mobile.

**Comment by AniketMalik** [comment]
I have thoroughly checked for this issue on my end and have come to the conclusion that this issue is not caused by the application or woostore pro api wordpress plugin. It is related to some caching setting on the website or from some other plugin which caches the REST API and updates the previous cart in the checkout page even though the updated cart has different contents.

This could be verified by this following method:
1. Add products to cart.
2. Remove any item from cart.
3. Refresh the cart from the reload button at the top. Here you will notice that the cart items are consistent and works as expected. However when you open the checkout page which is from the website, the cart items are loaded from the previous state of the cart which might be a result of caching. Now as the previous state of cart is used to show contents on the checkout page, the woostore pro api updates the cart yet again using those cached or previous contents and marks them as new. Now if you refresh the  cart in the application you will notice that the previous items are being added again as the cart was updated on the checkout page on the website with the previous items. 

The issue is likely caused by a conflict with some other plugin in your website or some sort of caching mechanism which could be within some other plugin like elementor pro ( this is just an example, do not take it literally ). 

The best course of action is to find out the conflict causing plugin and disabling the feature which is the root cause of this. I have seen the same issue previously with other customer who have caching enabled by default or there is some sort of caching of cart and checkout page by any plugin which manipulates the data being used in the checkout page which causes the issue. Once it is turned off, you will see that the issue will be resolved.

**Comment by Emicloud91** [comment]
Okay, thank you so much for you research and help! I've checked disabling plugins and yeah, you're right, it's indeed the Elementor Pro plugin which is causing the reset of the cart....I've disabled (my entire site broke in style XD) and then tried to add as many products as I could without problems...

Now the problem is: I cannot disable Elementor Pro because the entire site is build over it...is there anything like a snippet or any modification that I can approach to avoid the cart reset bug? :/

Thank you again for you help!

**Comment by AniketMalik** [comment]
You can contact the admin team of Elementor Pro to check if they have a
setting to disable just the cart and checkout page caching. Do just that
should resolve the issue and your website won't have to suffer.

**Comment by Emicloud91** [comment]
Oh, that's too bad, I thought that it could be solved disabling some easy option or workaround, as I need to deliver the App as soon as possible and Elementor support is normally slow...Another thing I noticed is that, when I activate the plugin, the cart goes back to zero (I previously had some items before activating WooStore Api)...I'll probably won't be able to use the template. :(

Thanks for the help

**Comment by AniketMalik** [comment]
Please search some option in the elementor settings where you can turn off
the caching for checkout page. That shall do the trick.

You just need to find the setting in elementor pro for checkout page, turn
off the cache and you'll be good to go.

**Comment by AniketMalik** [comment]
Do not post the login information here as it could be misused by anyone.

Moreover, I would love to help but as this is related to another plugins
functionality, I am afraid I won't be of much assistance to you.

Kindly checkout the documentation from elementor pro.

One another way could be to use the default Checkout page that comes from
WooCommerce instead of the one creadted by Elementor pro. You can change
that from WooCommerce settings. That checkout page can also be modified to
suit your needs.
